# Site settings
baseurl = "http://www.rotaractblois.com/"
languageCode = "fr"
title = "Rotaract Club de Blois"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Rotaract Club de Blois"
	description = "Association de jeunes étudiants / actifs !"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "Rotaractclubdeblois@gmail.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Rotaract Club de Blois"

	# About section
	#
	# Replace the 'logo_rotaract.png' under 'static/img' with your own image.
	[params.about]
		title = "Le Rotaract Club de Blois"
        devise1 = "Vous présente son engagement, "
		devise2 = "ainsi que ses projets."
		devise3 = "Le Rotaract renaît !"
		bio = "Le Rotaract est un club service parrainé par le Rotary. Cette association jeunesse regroupe des jeunes entre 18 et 30 ans. Le Rotaract se réunit pour mettre en place des actions de solidarités."
#		bio_text_redirect_mail = "Les portes du Rotaract de Blois sont ouvertes à tout le monde !!!"
		bio_redirect_mail = "Vous êtes intéressé ? Motivé ?"
#        bio_titre_devise = "Notre devise : "
        bio_devise = " **« L’AMITIÉ PAR LE SERVICE »** "
        bio_titre_ojbectifs = "Nos Objectifs :"
        bio_objectifs = "Les objectifs des clubs Rotaract consistent à mener des actions d’intérêt public (oeuvrer pour le bien d’autrui), d’actions internationales (développer des actions humanitaires par-delà les frontières, favoriser l’entente internationale (en accueillant par exemple des étudiants étrangers), d’actions intérieures (coordonner des actions d’utilité publique au niveau local), et d’actions professionnelles (organiser des conférences afin de faire partager à tous des expériences dans le domaine professionnel ou culturel)."
        bio_titre_nous_a_blois = "Nous, à Blois :"
        bio_nous_a_blois = "Aujourd’hui Blois est un petit groupe de jeunes professionnels et étudiants réunis pour créer en 2017-2018 une action Hors'Aract, 2019 sera la seconde émission, afin de pouvoir faire des dons à l’I.M.E. du Val de Loire et plein d'autres actions encore."
#        Les portes du Rotaract de Blois sont ouvertes à tout le
#        monde.
#
#        Vous êtes intéressé, motivé ?
#        Venez à une de ses réunions en tant qu’invité. Et
#        devenez par la suite, si vous le souhaitez, un membre du
#        Rotaract.



#    [[params.about.skills]]
#    name = "Communication"
#    value = 9
#
#    [[params.about.skills]]
#    name = "Organization"
#    value = 7
#
#    [[params.about.skills]]
#    name = "Learning"
#    value = 10
#
#    [[params.about.skills]]
#        name = "Teaching"
#        value = 6
#
#    [[params.about.skills]]
#        name = "Planning"
#        value = 7
#
#    [[params.about.skills]]
#        name = "Visual Design"
#        value = 5
#
#    [[params.about.skills]]
#        name = "UX Design"
#        value = 8
#
#    [[params.about.skills]]
#        name = "Programming"
#        value = 6

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "facebook"
			link = "https://www.facebook.com/RotaractBloisOfficiel/"


	[params.form]
		title = "Nous rejoindre !"
		# Form fields
		name = "Nom"
		email = "Email"
		message = "Message"
		buttonText = "Envoyer"


	[params.footer]
		copyright = "© 2019 by Rotaract. All rights reserved."
